UnitDirectory/Pages/CreateUnit.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UnitDirectory.Application.Commands.AddUnit;

namespace UnitDirectory.Pages
{
    [IgnoreAntiforgeryToken]
    public class CreateUnitModel : PageModel
    {
        private readonly IMediator _mediator;

        [BindProperty]
        public AddUnitCommand Data { get; set; } = new();

        public CreateUnitModel(IMediator mediator)
        {
            _mediator = mediator;
        }
        public IActionResult OnGet(Guid id)
        {
            Data.ParentId = id;

            return Page();
        }


        public async Task<IActionResult> OnPostAsync(Guid id)
        {
            Data.ParentId = id;
            await _mediator.Send(Data);

            return RedirectToPage("Index");
        }
    }
}

UnitDirectory/Pages/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UnitDirectory.Application.Commands.DeleteUnit;
using UnitDirectory.Application.Queries.ExportUnitList;
using UnitDirectory.Application.Queries.GetUnitList;
using UnitDirectory.Core.Dtos;

namespace UnitDirectory.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;

        public IEnumerable<UnitDto> Units { get; private set; }

        public IndexModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync()
        {
            Units = await _mediator.Send(new GetUnitListQuery());
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            await _mediator.Send(new DeleteUnitCommand { Id = id });

            return RedirectToPage();
        }

        public IActionResult OnPostRefresh()
        {
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostExport()
        {
            using var stream = new MemoryStream();
            using var writer = new StreamWriter(stream);
            var units = await _mediator.Send(new ExportUnitListQuery());
            var unitArray = units.ToArray();
            var serializer = new System.Xml.Serialization.XmlSerializer(typeof(Core.Entities.Unit[]));
            serializer.Serialize(stream, unitArray);
            var byteArray = stream.ToArray();

            return File(byteArray, "text/xml", $"Export-{DateTime.Now.ToString("yyy-MM-dd-hh-mm-ss")}.xml");
        }
    }
}

UnitDirectory/Pages/MoveUnit.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UnitDirectory.Application.Commands.MoveUnit;
using UnitDirectory.Application.Queries.GetUnitListToMove;
using UnitDirectory.Core.Dtos;

namespace UnitDirectory.Pages
{
    public class MoveUnitModel : PageModel
    {
        private readonly IMediator _mediator;

        [BindProperty]
        public Guid Id { get; set; }
        public IEnumerable<UnitDto> Units { get; private set; }

        public MoveUnitModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync(Guid id)
        {
            Id = id;
            Units = await _mediator.Send(new GetUnitListToMoveQuery { Id = id });
        }

        public async Task<IActionResult> OnPostPatchAsync(Guid parentId)
        {
            await _mediator.Send(new MoveUnitCommand { Id = Id, ParentId = parentId });

            return RedirectToPage("Index");
        }
    }
}

UnitDirectory/Pages/CreateUnit.cshtml
@page "{id:Guid}"
@model UnitDirectory.Pages.CreateUnitModel
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}


<h2>Add a child unit</h2>
<form method="post">
    <input name="id" value="@Model.Data.ParentId" type="hidden" />
    <p><label>Name</label><br />
        <input name="name" />
    </p>
    <input type="submit" value="Отправить" />
</form>

UnitDirectory/Pages/Index.cshtml
@page
@model UnitDirectory.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<div class="container">
    <header class="d-flex justify-content-center py-3">
        <form method="post">
            <button type="submit" class="btn btn-link" asp-page-handler="refresh">
                Refresh
            </button>  
            <button type="submit" class="btn btn-link" asp-page-handler="export">
                Export XML
            </button>
        </form>
    </header>
  </div>

<main class="container">
  <div class="bg-light p-5 rounded">
    <ul class="list-group list-group-flush">
        @foreach (var unit in Model.Units)
        {
            <li class="list-group-item" style="padding-left:@(unit.Level * 50)px">

                <div class="fw-bold">@($"{unit.Name} {unit.Index}")</div>
                <form method="post">
                    <a  class="btn btn-link" asp-page="CreateUnit" asp-route-id="@unit.Id">Add New Child</a>
                    @if(unit.ParentId is not null)
                    {
                        <a class="btn btn-link"  asp-page="MoveUnit" asp-route-id="@unit.Id">MoveUnit</a>

                        <button type="submit" class="btn btn-link" asp-page-handler="delete" asp-route-id="@unit.Id">
                            Delete
                        </button>                            
                    }
                </form>
            </li>
        }
    </ul>


  </div>
</main>

UnitDirectory/Pages/MoveUnit.cshtml
@page
@model UnitDirectory.Pages.MoveUnitModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<main class="container">
  <div class="bg-light p-5 rounded">
    <ul class="list-group list-group-flush">
        <form method="post">
            <input name="id" value="@Model.Id" type="hidden" />
            @foreach (var unit in Model.Units)
            {
                <li class="list-group-item" style="padding-left:@(unit.Level * 50)px">

                    <div class="fw-bold">@($"{unit.Name} {unit.Index}")</div>

                    <button class="btn btn-link" type="submit"  asp-page-handler="patch" asp-route-parentId="@unit.Id">
                        Move Here
                    </button>                         
                </li>
            }
        </form>
    </ul>


  </div>
</main>

UnitDirectory/Pages/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Unit Directory</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <div>
        @RenderBody()
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>